
INSERT INTO tb_material(name, amount) VALUES ('Iron', 70);
INSERT INTO tb_material(name, amount) VALUES ('wood', 20);
INSERT INTO tb_material(name, amount) VALUES ('copper', 120);
INSERT INTO tb_material(name, amount) VALUES ('Tin', 50);
INSERT INTO tb_material(name, amount) VALUES ('Lead', 320);
INSERT INTO tb_material(name, amount) VALUES ('Sand', 430);
INSERT INTO tb_material(name, amount) VALUES ('Wool', 200);
INSERT INTO tb_material(name, amount) VALUES ('Gold', 300);
INSERT INTO tb_material(name, amount) VALUES ('bronze', 102);

create table provider (value float8, raw_material_id int8 not null, product_id int8 not null, material_id int8 not null, primary key (product_id, raw_material_id));
create table tb_material (material_id int8 generated by default as identity, amount int4, name varchar(255), primary key (material_id));
create table tb_product (product_id int8 generated by default as identity, amount int4, cost int4, name varchar(255), primary key (product_id));
alter table if exists provider add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq foreign key (raw_material_id) references tb_material;
alter table if exists provider add constraint FKs0ii9ltwn61fipb9at3oxpn64 foreign key (product_id) references tb_product;
alter table if exists provider add constraint FKpsan5msmovpf3tlrx94utqu1v foreign key (material_id) references tb_material;
create table provider (value float8, raw_material_id int8 not null, product_id int8 not null, material_id int8 not null, primary key (product_id, raw_material_id));
create table tb_material (material_id int8 generated by default as identity, amount int4, name varchar(255), primary key (material_id));
create table tb_product (product_id int8 generated by default as identity, amount int4, cost int4, name varchar(255), primary key (product_id));
alter table if exists provider add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq foreign key (raw_material_id) references tb_material;
alter table if exists provider add constraint FKs0ii9ltwn61fipb9at3oxpn64 foreign key (product_id) references tb_product;
alter table if exists provider add constraint FKpsan5msmovpf3tlrx94utqu1v foreign key (material_id) references tb_material;
create table provider (value float8, raw_material_id int8 not null, product_id int8 not null, material_id int8 not null, primary key (product_id, raw_material_id));
create table tb_material (material_id int8 generated by default as identity, amount int4, name varchar(255), primary key (material_id));
create table tb_product (product_id int8 generated by default as identity, amount int4, cost int4, name varchar(255), primary key (product_id));
alter table if exists provider add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq foreign key (raw_material_id) references tb_material;
alter table if exists provider add constraint FKs0ii9ltwn61fipb9at3oxpn64 foreign key (product_id) references tb_product;
alter table if exists provider add constraint FKpsan5msmovpf3tlrx94utqu1v foreign key (material_id) references tb_material;
create table provider (value float8, raw_material_id int8 not null, product_id int8 not null, material_id int8 not null, primary key (product_id, raw_material_id));
create table tb_material (material_id int8 generated by default as identity, amount int4, name varchar(255), primary key (material_id));
create table tb_product (product_id int8 generated by default as identity, amount int4, cost int4, name varchar(255), primary key (product_id));
alter table if exists provider add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq foreign key (raw_material_id) references tb_material;
alter table if exists provider add constraint FKs0ii9ltwn61fipb9at3oxpn64 foreign key (product_id) references tb_product;
alter table if exists provider add constraint FKpsan5msmovpf3tlrx94utqu1v foreign key (material_id) references tb_material;
create table provider (value float8, raw_material_id int8 not null, product_id int8 not null, material_id int8 not null, primary key (product_id, raw_material_id));
create table tb_material (material_id int8 generated by default as identity, amount int4, name varchar(255), primary key (material_id));
create table tb_product (product_id int8 generated by default as identity, amount int4, cost int4, name varchar(255), primary key (product_id));
alter table if exists provider add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq foreign key (raw_material_id) references tb_material;
alter table if exists provider add constraint FKs0ii9ltwn61fipb9at3oxpn64 foreign key (product_id) references tb_product;
alter table if exists provider add constraint FKpsan5msmovpf3tlrx94utqu1v foreign key (material_id) references tb_material;
create table provider (value float8, raw_material_id int8 not null, product_id int8 not null, material_id int8 not null, primary key (product_id, raw_material_id));
create table tb_material (material_id int8 generated by default as identity, amount int4, name varchar(255), primary key (material_id));
create table tb_product (product_id int8 generated by default as identity, amount int4, cost int4, name varchar(255), primary key (product_id));
alter table if exists provider add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq foreign key (raw_material_id) references tb_material;
alter table if exists provider add constraint FKs0ii9ltwn61fipb9at3oxpn64 foreign key (product_id) references tb_product;
alter table if exists provider add constraint FKpsan5msmovpf3tlrx94utqu1v foreign key (material_id) references tb_material;
create table provider (value float8, raw_material_id int8 not null, product_id int8 not null, material_id int8 not null, primary key (product_id, raw_material_id));
create table tb_material (material_id int8 generated by default as identity, amount int4, name varchar(255), primary key (material_id));
create table tb_product (product_id int8 generated by default as identity, amount int4, cost int4, name varchar(255), primary key (product_id));
alter table if exists provider add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq foreign key (raw_material_id) references tb_material;
alter table if exists provider add constraint FKs0ii9ltwn61fipb9at3oxpn64 foreign key (product_id) references tb_product;
alter table if exists provider add constraint FKpsan5msmovpf3tlrx94utqu1v foreign key (material_id) references tb_material;
create table provider (value float8, raw_material_id int8 not null, product_id int8 not null, material_id int8 not null, primary key (product_id, raw_material_id));
create table tb_material (material_id int8 generated by default as identity, amount int4, name varchar(255), primary key (material_id));
create table tb_product (product_id int8 generated by default as identity, amount int4, cost int4, name varchar(255), primary key (product_id));
alter table if exists provider add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq foreign key (raw_material_id) references tb_material;
alter table if exists provider add constraint FKs0ii9ltwn61fipb9at3oxpn64 foreign key (product_id) references tb_product;
alter table if exists provider add constraint FKpsan5msmovpf3tlrx94utqu1v foreign key (material_id) references tb_material;

    create table provider (
       value float8,
        raw_material_id int8 not null,
        product_id int8 not null,
        material_id int8 not null,
        primary key (product_id, raw_material_id)
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost int4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists provider 
       add constraint FKsyqf7wh5bcw2vq2arvmtjy2dq 
       foreign key (raw_material_id) 
       references tb_material;

    alter table if exists provider 
       add constraint FKs0ii9ltwn61fipb9at3oxpn64 
       foreign key (product_id) 
       references tb_product;

    alter table if exists provider 
       add constraint FKpsan5msmovpf3tlrx94utqu1v 
       foreign key (material_id) 
       references tb_material;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost int4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost int4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost int4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost int4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost int4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost int4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost float4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost int4,
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        created_on timestamp,
        email varchar(255),
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        phone_number varchar(255),
        updated_on timestamp,
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_materials (
       materials_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (materials_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_materials (
       materials_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (materials_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_materials (
       materials_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (materials_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;

    create table auth_authority (
       id int8 generated by default as identity,
        role_code varchar(255),
        role_description varchar(255),
        primary key (id)
    );

    create table auth_user_authority (
       user_id int8 not null,
        authorities_id int8 not null
    );

    create table auth_user_details (
       id int8 generated by default as identity,
        enabled boolean,
        first_name varchar(255),
        last_name varchar(255),
        user_key varchar(255),
        user_name varchar(255),
        primary key (id)
    );

    create table product_material (
       product_fk int8 not null,
        material_fk int8 not null
    );

    create table tb_material (
       material_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (material_id)
    );

    create table tb_materials (
       materials_id int8 generated by default as identity,
        amount int4,
        name varchar(255),
        primary key (materials_id)
    );

    create table tb_product (
       product_id int8 generated by default as identity,
        amount int4,
        cost varchar(255),
        name varchar(255),
        primary key (product_id)
    );

    alter table if exists auth_user_details 
       add constraint UK_7fx13tfge5grrevwfx5qqwdxn unique (user_name);

    alter table if exists auth_user_authority 
       add constraint FKn7t2r8oft6j1w61po11wnb19w 
       foreign key (authorities_id) 
       references auth_authority;

    alter table if exists auth_user_authority 
       add constraint FKo4vmid5kx45903pdsst9qu1p0 
       foreign key (user_id) 
       references auth_user_details;

    alter table if exists product_material 
       add constraint FKbocc2586nrdgsjcrgwfj9gl2s 
       foreign key (material_fk) 
       references tb_material;

    alter table if exists product_material 
       add constraint FK4bxyqy0465tc9ysf0ik5raj3l 
       foreign key (product_fk) 
       references tb_product;
